### ISSUE TITLE
Kanban Project Review(Javascript Capstone Project)

### ISSUE THREAD

**Issue by RileyManda** [RileyManda/javascript-capstone-project#21]
[Link to Kanban project](https://github.com/RileyManda/javascript-capstone-project/projects/1)

Dear reviewers,

We would like to inform you that we are currently a team of two people on this project. (@CELYNEBIRUNGI  and @RileyManda )

Please kindly review our [project Kanban implementation/setup](https://github.com/RileyManda/javascript-capstone-project/projects/1) and provide feedback and recommendations.

Thank you

Kind regards

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @RileyManda and @CELYNEBIRUNGI,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly provide the link to the Kanban board, not your repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by RileyManda** [comment]
Dear @TedLivist 

Thank you for your feedback on your submission.
We submitted a link to the project as per instructions in the project submission [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md)
Please see screenshot below:
<img width="983" alt="Screen Shot 2023-07-03 at 12 46 12 PM" src="https://github.com/RileyManda/javascript-capstone-project/assets/37291194/bafe9624-fc4f-4af8-912f-a4f52a1d9c1c">

**Comment by topeogunleye** [comment]
@RileyManda, please be informed that this is the kanban board the previous reviewer asked you to provide a link for:

<img width="960" alt="image" src="https://github.com/RileyManda/javascript-capstone-project/assets/52934128/7994ec0f-744b-43a1-a3d1-2dfda13336f4">

**Comment by RileyManda** [comment]
@topeogunleye 

Thank you for your feedback.
I have updated the issue and included a link to the Kanban project.

**Comment by TedLivist** [comment]
Hi @RileyManda I think if you look at the item before that one you can see it asks you to add the link to the project in the issue, which you would submit.

![image](https://github.com/RileyManda/javascript-capstone-project/assets/36542986/d03558cb-c647-4814-9d2c-0c77535c92ff)

**Comment by topeogunleye** [comment]
Hi @RileyManda, @CELYNEBIRUNGI, 

Thank you for submitting your project for code review.  :shipit: 
Congratulations! 🎉 

![dwayne-the-rock](https://user-images.githubusercontent.com/52934128/180645370-67438f1f-e27d-4f8b-88d6-1e3474394f0a.gif)

## (Highlights) Good Points: 💪 
👋 Hello, thank you for submitting your project for code review. Here's a summary of your code review:

👉 You provided a link to your GitHub project and the number of people in your group in the GitHub issue. That's good!

👉 You copied the template board correctly and removed the cards with the Student C suffix as you are a team of two people. Well done!

👉 You assigned all cards to team members in a fair way. You decided who is Student A and Student B and assigned the cards accordingly. You also assigned the group tasks to someone. Great job!

👉 Your board looks neat and organized. You have 15 cards in total and they are distributed in different columns according to your progress.

👉 Keep up the good work! 😊
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
